import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { createPullRequest, buildPullRequestBody } from "../src/pr.js";

test("createPullRequest dry-run builds gh command from latest passed run", async () => {
  const cwd = await mkdtemp(path.join(os.tmpdir(), "yololoop-pr-"));
  await mkdir(path.join(cwd, ".yololoop/runs"), { recursive: true });
  await writeFile(path.join(cwd, ".yololoop/runs/run-20260616T010000Z.json"), JSON.stringify({
    version: 0,
    createdAt: "2026-06-16T01:00:00.000Z",
    status: "passed",
    path: ".yololoop/runs/run-20260616T010000Z.json",
    item: {
      title: "chore: Add parser test"
    },
    branch: {
      enabled: true,
      name: "chore/add-parser-test"
    },
    gates: [
      {
        name: "tests",
        ok: true
      }
    ]
  }), "utf8");

  const result = await createPullRequest(cwd, { dryRun: true, draft: true, base: "main" });

  assert.equal(result.title, "chore: Add parser test");
  assert.equal(result.head, "chore/add-parser-test");
  assert.equal(result.base, "main");
  assert.deepEqual(result.command.slice(0, 4), ["gh", "pr", "create", "--base"]);
  assert.equal(result.command.at(-1), "--draft");
});

test("buildPullRequestBody includes run artifact and gates", () => {
  const body = buildPullRequestBody({
    status: "passed",
    path: ".yololoop/runs/run.json",
    item: {
      title: "bug: Fix status"
    },
    gates: [
      {
        name: "lint",
        ok: true
      }
    ]
  });

  assert.match(body, /Generated by yololoop/);
  assert.match(body, /bug: Fix status/);
  assert.match(body, /lint: passed/);
});
