import { spawnSync } from "node:child_process";
import { readLatestJson } from "./status.js";
import { ensureGitRepo } from "./git.js";
import { UserError } from "./errors.js";

export async function createPullRequest(cwd, options = {}) {
  const latestRun = await readLatestJson(cwd, ".yololoop/runs");
  if (!latestRun) {
    throw new UserError("no run artifact found; run yololoop run --once first");
  }

  if (latestRun.status !== "passed") {
    throw new UserError(`latest run status is ${latestRun.status}; only passed runs can open PRs`);
  }

  if (!latestRun.branch?.enabled) {
    throw new UserError("latest run used --no-branch; rerun with branch creation before opening a PR");
  }

  const title = latestRun.item?.title ?? "yololoop run";
  const head = latestRun.branch.name;
  const base = options.base ?? "main";
  const body = buildPullRequestBody(latestRun);
  const command = [
    "gh",
    "pr",
    "create",
    "--base",
    base,
    "--head",
    head,
    "--title",
    title,
    "--body",
    body,
    ...(options.draft ? ["--draft"] : [])
  ];

  if (options.dryRun) {
    return {
      dryRun: true,
      title,
      head,
      base,
      body,
      command
    };
  }

  ensureGitRepo(cwd);
  runChecked(cwd, "git", ["push", "-u", "origin", head]);
  const result = runChecked(cwd, command[0], command.slice(1));

  return {
    dryRun: false,
    title,
    head,
    base,
    body,
    url: result.stdout.trim()
  };
}

export function buildPullRequestBody(run) {
  const gateLines = (run.gates ?? []).map((gate) => (
    `- ${gate.name ?? gate.command}: ${gate.ok ? "passed" : "failed"}`
  ));

  return [
    "Generated by yololoop.",
    "",
    `Backlog item: ${run.item?.title ?? "<unknown>"}`,
    `Run artifact: ${run.path ?? "<unknown>"}`,
    `Run status: ${run.status}`,
    "",
    "Gates:",
    ...(gateLines.length > 0 ? gateLines : ["- none configured"])
  ].join("\n");
}

function runChecked(cwd, command, args) {
  const result = spawnSync(command, args, {
    cwd,
    encoding: "utf8"
  });

  if (result.status !== 0) {
    throw new UserError(`${command} failed: ${result.stderr.trim() || result.stdout.trim() || result.error?.message}`);
  }

  return result;
}
